# Generated by Django 5.0 on 2023-12-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_hash', models.CharField(max_length=50)),
                ('product_seria_num', models.IntegerField()),
                ('made_in', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('utilized', models.BooleanField(default=False)),
                ('utilized_date', models.DateField(null=True)),
            ],
        ),
    ]
