# Generated by Django 5.0 on 2023-12-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
